### PR TITLE
Fixed bug in referencing igraph

### PR DESCRIPTION
**Pull request by dafnevk**
The module igraph is aliased `_ig`, not `ig`

### CODE REVIEW

**Comment by vtraag** [comment]
Thanks for the fix! However, the naming was intentional, to mark the module as "private" (see _single_leading_underscore in [PEP8](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles)). Is there any specific reason why it should be renamed?

**Comment by dafnevk** [comment]
Sorry, maybe my comment was confusing. I don't think alias `_ig` should be renamed, there was just a bug where accidentally a call to `ig` was made (see commit).

**Comment by vtraag** [comment]
Ah, sorry! I checked it on my mobile, and for some reason it seemed as if you renamed to `ig`, instead of keeping the name `_ig`. I'll merge the PR. Thanks! If you have any other issues (or immediate fixes), do let me know.

**Comment by gokceneraslan** [comment]
This fix is not in the released package, right? So shall I just switch to leidenalg?

**Comment by vtraag** [comment]
No, that is right. There are no plans to make any new releases for the `louvain-igraph` package, and will not be updated further. Please switch to [`leidenalg`](https://github.com/vtraag/leidenalg) indeed.

**Pull request merged**
